apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: jgr-designer-sfleads
  namespace: tools
spec:
  adminServerSecure: true
  createDashboardUsers: true
  designerFlowsOperationMode: local
  designerFlowsType: api-flows
  enableMetrics: true
  license:
    accept: true
    license: L-APEH-CCHL5W
    use: CloudPakForIntegrationNonProduction
  pod:
    containers:
      runtime:
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 512Mi
  replicas: 1
  router:
    timeout: 300s
  service:
    endpointType: http
  version: 12.0-lts
  barURL: >-
    https://github.com/gomezrjo/cp4idemo/raw/main/barfiles/SFLeads.bar
  configurations:
    - github-barauth
    - ace-sf-designer-account
  tracing:
    enabled: true
    namespace: tools